app/auth.py
# auth.py

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from app.models import User, Codes, Groups
from . import db
from iqsms_rest import Gate
import random
import time
from .config import *

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template('auth/login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    user = User.query.filter_by(email=email).first()
    print(user)
    if not user or not check_password_hash(user.password, password):
        flash('Неверный пароль')
        return redirect(url_for('auth.login'))
    if user.role not in [1, 2]:
        #if not user.confirmed:
         #   flash('Подтвердите номер телефона')
          #  return redirect(url_for('auth.login'))
        flash('Нет доступа')
        return redirect(url_for('auth.login'))
    login_user(user, remember=remember)
    return redirect(url_for('main.index'))


@auth.route('/restore-pass', methods=['GET'])
def restore_pass():
    return render_template('auth/restore_pass.html')


@auth.route('/restore-pass', methods=['POST'])
def restore_pass_post():
    phone = request.form.get('phone').replace('+', '').replace(' ', '').replace('-', '').replace('(', '').replace(')',
                                                                                                                  '')
    user = User.query.filter_by(phone=phone).first()
    if not user or user.status != 'admin':
        flash('Пользователь не найден или не имеет доступ к панели администратора')
        return redirect(url_for('auth.login'))
    code = random.randint(1001, 9999)
    new_code = Codes(code=code, phone=phone)
    db.session.add(new_code)
    db.session.commit()
    sender = Gate(SMS_LOGIN, SMS_PASSWORD)
    status = sender.send_message(phone, f'Ваш код сброса пароля\n{code}', 'SMS DUCKOHT')

    return render_template('auth/check_code.html', phone=phone)


@auth.route('/check-code', methods=['POST'])
def check_code():
    phone = request.args.get('phone')
    code = Codes.query.filter_by(phone=phone).all()[-1].code
    user_input = request.form.get('code')

    if code != user_input:
        flash('Неверный код')
        return render_template('auth/check_code.html', phone=phone)

    return render_template('auth/new_password.html', phone=phone)


@auth.route('/set-password', methods=['POST'])
def set_password():
    phone = request.args.get('phone')
    password = request.form.get('password')
    conf_password = request.form.get('conf_password')
    if password != conf_password:
        flash('Пароли не совпадают')
        return render_template('auth/new_password.html')
    _ = User.query.filter_by(phone=phone).update({'password': generate_password_hash(password, method='sha256')})
    db.session.commit()
    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/profile')
def profile():
    user = {
        'name': current_user.name,
        'email': current_user.email,
        'phone': current_user.phone,
        'phone_confirmed': current_user.confirmed,
        'status': 'Активный' if current_user.status == 'active' else 'Заблокирован',
        'role': 'Пользователь' if current_user.role == 0 else f'Админ сети {Groups.query.filter_by(id=current_user.group).first().name}' if current_user.role == 1 else 'Админ сервиса',
        'group': Groups.query.filter_by(id=current_user.group).first().name,

    }
    return render_template('profile.html', user=user)


@auth.route('/edit_profile', methods=['POST'])
def edit_profile():
    name = request.args.get('name')
    email = request.args.get('email')
    phone = str(request.args.get('phone')).replace('(', '').replace(')', '').replace('-', '').replace('+', '').replace(
        ' ', '')
    _ = User.query.filter_by(id=current_user.id).update({'name': name, 'phone': phone, 'email': email})
    db.session.commit()
    return redirect(url_for('auth.profile'))


@auth.route('/webapi/edit_password', methods=['POST'])
def edit_password():
    old_password = request.form.get('old_password')
    new_password = request.form.get('new_password')
    conf_password = request.form.get('conf_password')
    print(old_password, new_password, conf_password)
    if not check_password_hash(current_user.password, old_password):
        return {'status': False, 'error': 'Неверный старый пароль'}
    if conf_password != new_password:
        return {'status': False, 'error': 'Пароли не совпадают'}
    _ = User.query.filter_by(id=current_user.id).update({'password':  generate_password_hash(new_password, method='sha256')})
    db.session.commit()
    return {'status': True}

app/chats/__init__.py
from flask import Blueprint

main = Blueprint('chats', __name__)

app/templates/news/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('chats.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('chats.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/news/new.html
<!-- templates/stats.html -->

{% extends "base.html" %}

{% block content %}
    <style>
        h6 {
            font-size: 28px !important;
            color: #012970 !important;
            font-weight: 700 !important;
            margin: 0 !important;
            padding: 0 !important;
        }

        label {
            font-size: 15px;
            font-weight: 600;
            color: #4154f1;
            padding: 10px 15px;
            border-radius: 4px;
        }

        li .form-control {
            width: 90%;
        }
    </style>
    <style>
        form {
            max-width: fit-content;
        }

        .card-title {
            font-size: 18px;
        }

        .form-control {
            font-size: 16px;
        }

        .form-select {
            font-size: 16px;
        }

        .btn {
            font-size: 16px;
        }


        .tab.active {
            background-color: #5071BF4D !important;
        }


        .tab:hover {
            background-color: #5071BF4D !important;
        }

        tr.active {
            background-color: #5071BF4D !important;
        }

        p {
            font-size: 16px;
        }


        tr:hover {
            background-color: #5071BF4D !important;
        }

        table {
            margin-top: 40px;
        }

        th div {
            margin-top: -40px;
            position: absolute;
        }

        /* design */
        table {
            border-collapse: collapse;
        }

        tr:nth-child(even) {
            background: #EEE;
        }

        p.mytabs {
            font-size: 16px;
            margin: 1;
        }

        .profile-picture {
            position: relative;
        }

        .profile-delete {
            position: absolute;
            bottom: 0;
        }
    </style>
    <div class="pagetitle">
        <section class="section profile">
            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-title">
                            <div class="">
                                <div style="display: flex" class="col-xl-12">
                                    <a class=" left" type="button" href="{{ url_for('main.news') }}"><i
                                            style="font-size: 30px" class="bi bi-arrow-left-square"></i></a>
                                </div>


                            </div>
                            {{ jk.name }}
                        </div>
                        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                            <form method="post" action="{{ url_for('main.update_new', id=jk.id) }}" class="col-xl-12">
                                <div class="col-xl-12"
                                     style="justify-content: center;padding: 0;text-align: center;display: flex;">
                                    {% if not jk.photo1 and not jk.photo2 and not photo3 %}
                                        <div class="" style="justify-content: center;padding: 0;display: flex;">
                                            <h6 class="rounded-circle" style="height: 120px;max-width: 120px;">Нет
                                                фото</h6>
                                        </div>
                                    {% else %}

                                        {% if jk.photo1 %}
                                            <img src="{{ url_for('static', filename='news/'+jk.photo1) }}"
                                                 alt="Profile"
                                                 class="p-2 profile-picture" style="height: 120px;"/>
                                            <a href="/delete_picture_new/{{ jk.id }}/1"
                                               class="rounded-circle btn btn-info btn-sm profile-delete"><i
                                                    class="bi bi-trash"></i></a>
                                        {% else %}



                                        {% endif %}


                                        {% if jk.photo2 %}
                                            <img src="{{ url_for('static', filename='news/'+jk.photo2) }}"
                                                 alt="Profile"
                                                 class="p-2 profile-picture" style="height: 120px;"/>
                                            <a href="/delete_picture_new/{{ jk.id }}/2"
                                               class="rounded-circle btn btn-info btn-sm profile-delete"><i
                                                    class="bi bi-trash"></i></a>
                                        {% else %}
                                        {% endif %}

                                        {% if jk.photo3 %}

                                            <img src="{{ url_for('static', filename='news/'+jk.photo1) }}"
                                                 alt="Profile"
                                                 class="p-2 profile-picture" style="height: 120px;"/>
                                            <a href="/delete_picture_new/{{ jk.id }}/3"
                                               class="rounded-circle btn btn-info btn-sm profile-delete"><i
                                                    class="bi bi-trash"></i></a>
                                        {% else %}
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <br>
                                <div class="col-xl-12">
                                    {% if jk.blocked == 0 %}
                                        <p style="color:green">Показывается</p>
                                    {% else %}
                                        <p style="color:red">Заблокировано</p>
                                    {% endif %}
                                    <div class="row">
                                        <div class="col-xl-12">
                                            <b>Автор</b>
                                            <p>
                                                <a href="/user/{{ User.query.filter_by().first().id }}">{{ User.query.filter_by().first().name }} {{ User.query.filter_by().first().surname }}</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="addon1" name="name" placeholder="Заголовок"
                                           value="{{ jk.name }}" aria-describedby="button-addon1">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="button-addon1">X
                                        </button>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="{{ jk.description }}"
                                           name="description" placeholder="Описание"
                                           aria-describedby="button-addon2" id="addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="button-addon2">X
                                        </button>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="{{ jk.address }}" name="address"  placeholder="Адрес"
                                           aria-describedby="button-addon3" id="addon3">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="button-addon3">X
                                        </button>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="{{ jk.phone }}" name="phone" placeholder="Телефон"
                                           aria-describedby="button-addon4" id="addon4" data-phone-pattern>
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="button-addon4">X
                                        </button>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <select class="form-select" name="jk">
                                        {% for i in jks %}
                                            <option value="{{ i.id }}"
                                                    {% if i.id==jk.jk %}selected{% endif %}>{{ i.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="row">
                                    <div style="display: flex;" class="col-xl-6">
                                        <div class="left">
                                            <a href="/connect/{{ jk.id }}" class="btn btn-primary">Связаться</a>
                                            {% if jk.blocked != 0 %}
                                                <a href="/unblock_new/{{ jk.id }}"
                                                   class="btn btn-secondary">Разблокировать</a>
                                            {% else %}
                                                <a href="/block_new/{{ jk.id }}"
                                                   class="btn btn-secondary">Заблокировать</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div style="display: flex;" class="col-xl-6">
                                        <div class="right">
                                            <button type="submit"
                                                    class="btn btn-primary">Сохранить
                                            </button>
                                            <a href="{{ url_for('main.new', id=jk.id) }}"
                                               class="btn btn-secondary">Отменить</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                var eventCalllback = function (e) {
                    var el = e.target,
                        clearVal = el.dataset.phoneClear,
                        pattern = el.dataset.phonePattern,
                        matrix_def = "+7(___) ___-__-__",
                        matrix = pattern ? pattern : matrix_def,
                        i = 0,
                        def = matrix.replace(/\D/g, ""),
                        val = e.target.value.replace(/\D/g, "");
                    if (clearVal !== 'false' && e.type === 'blur') {
                        if (val.length < matrix.match(/([\_\d])/g).length) {
                            e.target.value = '';
                            return;
                        }
                    }
                    if (def.length >= val.length) val = def;
                    e.target.value = matrix.replace(/./g, function (a) {
                        return /[_\d]/.test(a) && i < val.length ? val.charAt(i++) : i >= val.length ? "" : a
                    });
                }
                var phone_inputs = document.querySelectorAll('[data-phone-pattern]');
                for (let elem of phone_inputs) {
                    for (let ev of ['input', 'blur', 'focus', 'load']) {
                        elem.addEventListener(ev, eventCalllback);
                    }
                }
            });
            {% for i in [1, 2, 3, 4, 6] %}
                document.getElementById("button-addon{{ i }}").onclick = function (e) {
                    document.getElementById("addon{{ i }}").value = "";
                };
            {% endfor %}
        </script>
    </div>

{% endblock %}